### ISSUE TITLE
Pixels get scrambled on top and bottom of third image

### ISSUE THREAD

**Issue by gadlol** [peakvisor/panorama#6]
Hi,

Thanks a lot for this code...

Please have a look at the images:

![2_top](https://user-images.githubusercontent.com/518451/50349862-d66f2000-0545-11e9-8afc-57ba8ae4aade.jpg)

![2_bottom](https://user-images.githubusercontent.com/518451/50349861-d5d68980-0545-11e9-93ba-18d2a1603349.jpg)

The top pixels ( 2 or 3 lines) are scrambled and bottom pixels (one line ) is white to gray.

Something is wrong with the algorithm... 

Note this happens only to the third image ( face = 2 )

**Comment by gadlol** [comment]
There is also a problem with the last image. The code adds white line on the top...

![top5](https://user-images.githubusercontent.com/518451/50479029-11a59f00-09dd-11e9-9698-ff9256f0dada.jpg)

**Comment by RichardMorris** [comment]
Could you post the source images which cause the problems. Or if that's a problem a problem the dimensions, and type of the image.

**Comment by gadlol** [comment]
The images are power of 2 and from my tests this happens to all images...

You can use the image that is in the code here ( equirectangular_panorama.jpg ).. It also produces the cubes with that problem...

![1](https://user-images.githubusercontent.com/518451/50480796-dc05b380-09e6-11e9-88ad-5ae8fcb8449b.jpg)

![2](https://user-images.githubusercontent.com/518451/50480803-df993a80-09e6-11e9-8469-b32b172f307c.jpg)

P.S. I am running the app in linux mint via the terminal...

**Comment by RichardMorris** [comment]
Confirmed for both problems.

I've found the problem with image 5. We need to using `>` rather than `>=` on line 166 of panorama.cpp, context is

				if (j<edge) {
					face = 4;
				} else if (j>=2*edge) {   // this is corrected code
					face = 5;
				} else {
					face = int(i/edge);
				}

**Comment by RichardMorris** [comment]
Looks like the above fix solves both problems.

**Comment by dangerden** [comment]
I've merged the changes. Thank you for the fix @RichardMorris !

**Comment by gadlol** [comment]
Thanks guys. it works now...
